---
- name: Set up the stable repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0640'

- name: Install packages
  package:
    name:
      - device-mapper-persistent-data
      - lvm2
      - docker-ce
      - docker-ce-cli

- name: Start / enable docker service
  systemd:
    name: docker
    enabled: true
    state: started
