---
- name: Set up the stable repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0640'

- name: Install packages
  package:
    name:
      - device-mapper-persistent-data
      - lvm2
      - docker-ce
      - docker-ce-cli

- name: Install python-docker-py for EL7
  package:
    name:
      - python-docker-py
  when: ansible_distribution_major_version == "7"

- name: Install python3-docker for EL8
  package:
    name:
      - python3-docker
  when: ansible_distribution_major_version == "8"

- name: Start / enable docker service
  systemd:
    name: docker
    enabled: true
    state: started
